### ISSUE TITLE
Provide the ability to run all test projects using a glob pattern

### ISSUE THREAD

**Issue by dgkanatsios** [joaoopereira/dotnet-test-rerun#117]
Currently, the DotNet test ADO task allows to run test projects using a glob pattern. For example,

```yaml
 - task: DotNetCoreCLI@2
      displayName: Run tests
      inputs:
        command: 'test'
        projects: 'src/**/*.[Tt]est?(s).csproj'
```

This will recursively search all folders for files matching this pattern. It would be great if the tool supported this.

PS. There is a workaround to add all test .csproj files to a solution (.sln). However, this increases the execution time, since on retry, the tool will try and search for the failed tests in all .csproj projects in the .sln file.
